METsoft/offers/urls.py
from django.conf.urls import include
from django.contrib.auth.decorators import permission_required
from django.urls import path, re_path
from django.views.generic import TemplateView
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r"offers", views.OfferViewSet)
router.register(r"materials", views.MaterialViewSet)
router.register(r"details", views.DetailViewSet)

urlpatterns = [
    re_path("^api/", include(router.urls)),
    path("test/", TemplateView.as_view(template_name="offers/test.html"), name="test"),
    path(
        "",
        TemplateView.as_view(template_name="offers/index_offers.html"),
        name="offers",
    ),
    path("create/", views.OfferCreateView.as_view(), name="offer-create"),
    path("<int:pk>/update/", views.OfferUpdateView.as_view(), name="offer-update"),
    path("<int:pk>/print/", views.OfferPrintView.as_view(), name="offer-print"),
    path("<int:pk>/details/", views.OfferDetailView.as_view(), name="offer-details"),
    path("notices/", views.OfferNoticesUpdateView.as_view(), name="notices"),
    path(
        "<int:pk>/details/create/",
        views.DetailCreateView.as_view(),
        name="detail-create",
    ),
    path(
        "<int:pk>/details/<int:det_pk>/update/",
        views.DetailUpdateView.as_view(),
        name="detail-update",
    ),
    path(
        "<int:pk>/details/<int:det_pk>/delete/",
        views.DetailDeleteView.as_view(),
        name="detail-delete",
    ),
    path(
        "details/",
        TemplateView.as_view(template_name="offers/details_index.html"),
        name="details-index",
    ),
    path(
        "details/searching/",
        views.DetailSearchingView.as_view(),
        name="details-searching",
    ),
    path(
        "materials/",
        TemplateView.as_view(template_name="offers/material_list.html"),
        name="materials",
    ),
    path(
        "materials/create/", views.MaterialCreateView.as_view(), name="material-create"
    ),
    path(
        "materials/<int:pk>/update/",
        views.MaterialUpdateView.as_view(),
        name="material-update",
    ),
    path("stats/", views.OffersStatisticsView.as_view(), name="offers-stats"),
]

METsoft/patterns/urls.py
from django.conf.urls import include
from django.urls import path, re_path
from django.views.generic import TemplateView
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r"patterns", views.PatternViewSet)

app_name = "patterns"
urlpatterns = [
    re_path("^api/", include(router.urls)),
    path(
        "",
        TemplateView.as_view(template_name="patterns/patterns_index.html"),
        name="patterns",
    ),
    path("<int:pk>/", views.PatternCardView.as_view(), name="pattern-card"),
    path("<int:pk>/edit", views.PatternUpdateView.as_view(), name="pattern-edit"),
    path("create/", views.PatternCreateView.as_view(), name="pattern-create"),
    path(
        "<int:pk>/status/",
        views.PatternStatusChangeView.as_view(),
        name="pattern-status-change",
    ),
    path("report/", views.PatternReportFormView.as_view(), name="pattern-report"),
]

METsoft/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, include
from django.views.generic import TemplateView
from rest_framework import routers

from . import views


router = routers.DefaultRouter()
router.register(r"logs", views.LogsViewSet, "logs")


urlpatterns = [
    path("", views.base),
    re_path("^api/", include(router.urls)),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="password-reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "redirect-after-login/", views.redirect_after_login, name="redirect-after-login"
    ),
    path(
        "logs/",
        TemplateView.as_view(template_name="users/logs_index.html"),
        name="logs",
    ),
]

METsoft/patterns/models.py
from datetime import date

from django.db import models
from django.urls import reverse


class PatternStatus(models.Model):
    status = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        db_table = "pattern_statuses"
        verbose_name_plural = "PatternStatuses"

    def __str__(self):
        return self.status


class Pattern(models.Model):
    customer = models.CharField("Nazwa firmy", max_length=100, blank=True, null=True)
    drawing_number = models.CharField(
        "Numer rysunku", max_length=100, blank=True, null=True
    )
    pattern_name = models.CharField(
        "Nazwa odlewu", max_length=100, blank=True, null=True
    )
    last_order = models.DateField(
        "Ostatnie zlecenie", blank=True, null=True, default=date.today
    )
    orders_amount = models.IntegerField(
        "Ilość zleceń", blank=True, null=True, default=1
    )
    area = models.FloatField("Powierzchnia", blank=True, null=True)
    layer_number = models.CharField(
        "Numer ułożenia", max_length=100, blank=True, null=True
    )
    layer_place = models.CharField(
        "Miejsce ułożenia", max_length=100, blank=True, null=True
    )
    material = models.CharField("Materiał", max_length=30, blank=True, null=True)
    cart_number = models.CharField(
        "Numer kartoteki", max_length=30, blank=True, null=True
    )
    pattern_index = models.CharField(
        "Numer indexu modelu", max_length=100, blank=True, null=True
    )
    verification = models.TextField("Weryfikacja", blank=True, null=True)
    remarks = models.TextField("Uwagi", blank=True, null=True)
    verification_date = models.CharField(
        "Data weryfikacji", max_length=30, blank=True, null=True, default=date.today
    )
    surname = models.CharField("Nazwisko", max_length=100, blank=True, null=True)
    status = models.ForeignKey(
        PatternStatus,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="status",
        default=1,
        limit_choices_to={"pk__lt": 8},
    )
    move_in = models.DateField(
        "Data zmiany statusu", blank=True, null=True, default=date.today
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "patterns"

    def __str__(self):
        return "{}".format(self.pattern_name)

    @staticmethod
    def get_absolute_url():
        return reverse("patterns:patterns")

    def get_not_using_time(self):
        if self.status.id in [4, 5, 6]:
            return None
        if self.last_order:
            diff = date.today() - self.last_order
            months = (diff.days // 365 * 12) + (diff.days % 365) / 30
            return int(months)
        return None

    def if_status_changed_update_history(self):
        previous_status = self.patternhistory_set.order_by("id").last()
        if previous_status.status != self.status:
            self.add_status_to_pattern_history()

    def add_status_to_pattern_history(self):
        PatternHistory.objects.create(
            pattern=self, status=self.status, date=self.move_in
        )


class PatternHistory(models.Model):
    pattern = models.ForeignKey(Pattern, on_delete=models.CASCADE, default=1)
    status = models.ForeignKey(PatternStatus, on_delete=models.DO_NOTHING, default=1)
    date = models.DateField()
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "pattern_history"
        verbose_name_plural = "PatternHistory"

METsoft/offers/forms.py
from django import forms

from .models import (
    AtestType,
    Detail,
    HeatTreatment,
    Notice,
    Offer,
    OfferPatternStatus,
    PatternTaper,
)


class OfferDetailsForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = ["notices", "status", "date_tech_out"]
        widgets = {
            "notices": forms.Textarea(attrs={"rows": 15, "cols": 100}),
        }


class OfferCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = ["offer_no", "client", "user_mark", "user_tech", "date_tech_in"]
        widgets = {
            "date_tech_in": forms.DateInput(
                attrs={"id": "datepicker1"}, format="%Y-%m-%d"
            )
        }


class DetailCreateForm(forms.ModelForm):

    pattern = forms.ModelChoiceField(
        queryset=OfferPatternStatus.objects.all(), required=False, label="Model",
    )

    heat_treat = forms.ModelChoiceField(
        queryset=HeatTreatment.objects.all(), required=False, label="Obróbka cieplna"
    )
    tapers = forms.ModelChoiceField(
        queryset=PatternTaper.objects.all(), required=False, label="Pochylenia"
    )
    atest = forms.ModelChoiceField(
        queryset=AtestType.objects.all(), required=False, label="Atest"
    )
    boxes = forms.CharField(
        label="Skrzynki formierskie",
        widget=forms.TextInput(attrs={"placeholder": "1,0 x 2,0 x 3,0"}),
        required=False,
    )

    class Meta:
        model = Detail
        fields = (
            "cast_name",
            "drawing_no",
            "mat",
            "draw_weight",
            "cast_weight",
            "pieces_amount",
            "detail_yield",
            "difficulty",
            "pattern",
            "heat_treat",
            "machining",
            "tolerances",
            "tapers",
            "atest",
            "required",
            "quality_class",
            "boxes",
            "others",
            "fr_chromite",
        )


class DetailUpdateForm(forms.ModelForm):
    class Meta:
        model = Detail
        exclude = (
            "offer",
            "fr_mold_work",
            "fr_mold_mat",
            "fr_fettling",
            "fr_welding",
            "fr_heating",
            "fr_scrap",
        )


class OfferNoticeForm(forms.ModelForm):
    class Meta:
        model = Notice
        fields = ["content"]
        widgets = {
            "content": forms.Textarea(attrs={"rows": 15, "cols": 100}),
        }


class DetailSearchingForm(forms.Form):

    drawing_no = forms.CharField(label="Wpisz nr rysunku:", required=False)
    cast_name = forms.CharField(label="Wpisz nazwę odlewu:", required=False)
    offer_no = forms.CharField(label="Wpisz nr oferyt:", required=False)

    class Meta:
        fields = ["drawing_no", "cast_name", "offer_no"]


class OfferStatsForm(forms.Form):
    date_stats_from = forms.DateField(
        label="Data początkowa",
        widget=forms.DateInput(
            attrs={"id": "datepicker1", "width": "275px"}, format="%Y-%m-%d",
        ),
    )
    date_stats_to = forms.DateField(
        label="Data końcowa",
        widget=forms.DateInput(
            attrs={"id": "datepicker2", "width": "275px"}, format="%Y-%m-%d",
        ),
    )

    class Meta:
        fields = ["date_stats_from", "date_stats_to"]

METsoft/offers/templates/offers/base.html
{% load static %}
<!doctype html>
<html lang="pl-PL">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
    <link rel="stylesheet", type="text/css" href="{% static 'bootstrap-4.3.1-dist/css/bootstrap.min.css' %}">
    <!-- <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap4.min.css"/> -->
    <link rel="stylesheet" type="text/css" href="{% static 'DataTables-1.10.20/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css'%}">
    <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/redmond/jquery-ui.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'jquery-ui-1.12.1/themes/redmond/jquery-ui.min.css' %}">

    {% block css %} {% endblock css %}

    <title>METsoft</title>
</head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-company-blue">
          <a class="navbar-brand" href="#">METsoft</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExample04">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item"><a class="nav-link" href="{% url 'offers' %}">Oferty</a></li>
                <li class="nav-item"><a class="nav-link" href="http://192.168.1.185/"  target="_blade">Kokila</a></li>

                {% if 'tech' in request.path or 'offers' in request.path or perms.tech_dep %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'orders-index' %}">Zlecenia</a></li>
                {% endif %}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Raporty (Kokila)</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown04">
                        <a class="dropdown-item"  href="{% url 'monitoring-in-work' %}" >Monitoring odlewów w produkcji</a>
                        <a class="dropdown-item" href="{% url 'monitoring-all' %}" >Monitoring odlewów (wszystkie zlecenia)</a>
                        <a class="dropdown-item" href="{% url 'finished' %}">Rejestr odbiorów</a>
                        <a class="dropdown-item" href="{% url 'pouring' %}">Rejestr zalań</a>
                        <a class="dropdown-item" href="{% url 'nonconformity' %}">Rejestr niezgodnych operacji</a>
                        <a class="dropdown-item" href="{% url 'molding' %}">Rejestr zaformowań</a>
                        <a class="dropdown-item" href="{% url 'non-destructive-testing' %}">Rejestr badań</a>
                        <a class="dropdown-item" href="{% url 'machining' %}">Rejestr wykonanych obróbek mechanicznych</a>
                        <a class="dropdown-item" href="{% url 'remarks' %}" >Rejestr uwag do zatwierdzonych operacji</a>
                        <a class="dropdown-item" href="{% url 'execution-time' %}"> Międzyczasy wykonania operacji</a>
                        <a class="dropdown-item" href="{% url 'weight-per-client' %}">Tonaż odlewów do wykonania wg klientów</a>
                        <a class="dropdown-item" href="{% url 'weight-per-group' %}" >Tonaż odlewów do wykonania wg grup kalkulacyjnych</a>
                        <a class="dropdown-item" href="{% url 'scraps' %}">Rejestr wybraków</a>
                        <a class="dropdown-item" href="{% url 'casting-weights' %}">Rejestr operacji ważenia</a>
                        <a class="dropdown-item" href="{% url 'casts-in-stock' %}"> Stan magazynowy</a>
                        <a class="dropdown-item" href="{% url 'inserted-data' %}">Rejest wpisanych danych</a>
                        <a class="dropdown-item" href="{% url 'yields' %}"> Uzyski wg KO</a>
                        <a class="dropdown-item" href="{% url 'castings-with-machining' %}"> Odlewy do obróbki mechanicznej</a>

                    </div>
                </li>


                {% if perms.offers or 'offers' in request.path or 'tech' in request.path %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'offer-create' %}">Dodaj ofertę</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Detale</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown04">
                            <a class="dropdown-item"  href="{% url 'details-index' %}" >Wszystkie</a>
                            <a class="dropdown-item" href="{% url 'details-searching' %}" >Wyszukiwanie</a>
                        </div>
                    </li>
                {% endif %}

                {% if perms.offers or 'offers' in request.path or 'tech' in request.path %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'materials' %}">Lista materiałów</a></li>
                {% endif %}

                {% if perms.offers %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Raporty (WZT)</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown04">
                        <a class="dropdown-item"  href="{% url 'offers-stats' %}" >Statystyki</a>
                        <a class="dropdown-item" href="{% url 'wzt-daily-report' %}" >Raport bieżący</a>
                    </div>
                </li>
                {% endif %}

                <li class="nav-item"><a class="nav-link" href="{% url 'patterns:patterns' %}">Modele</a></li>

                {% if perms.patterns.add_pattern %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'patterns:pattern-create' %}">Dodaj model</a></li>
                {% endif %}

                {% if 'patterns' in request.path or perms.patterns %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'patterns:pattern-report' %}">Raport (modele)</a></li>
                {% endif %}

                {% if request.user.username == 'admin' %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ustawienia</a>

                        <div class="dropdown-menu" aria-labelledby="dropdown04">
                            <a class="dropdown-item" href="{% url 'notices'%}">Domyślne uwagi</a>
                            <a class="dropdown-item" href="/admin/">Admin panel</a>
                        </div>
                    </li>
                {% endif %}
            </ul>

            <ul class="navbar-nav justify-content-end">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.first_name }}</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown05">
                            <a class="dropdown-item" href="{% url 'logout'%}">Wyloguj</a>
<!--                            <a class="dropdown-item" href="#">Profil</a>-->
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Zaloguj</a>
                    </li>
                {% endif %}
            </ul>
          </div>
        </nav>

        {% block content %} {% endblock content %}

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>-->
        <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>-->
        <!-- <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script> -->
        <script type="text/javascript" src="{% static 'jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>
        <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> -->
        <script type="text/javascript" src="{% static 'js/popper-1.15.0.js' %}"></script>
        <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->
        <script type="text/javascript" src="{% static 'bootstrap-4.3.1-dist/js/bootstrap.min.js' %}"></script>
        <!-- <script type="text/javascript" src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script> -->
        <script type="text/javascript" src="{% static 'DataTables-1.10.20/js/jquery.dataTables.min.js' %}"></script>
        <!-- <script type="text/javascript" src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js"></script> -->
        <script type="text/javascript" src="{% static 'DataTables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>


        {% block scripts %} {% endblock scripts %}

    <script>
        $(function() {
            $( "#datepicker1" ).datepicker({
                dateFormat: "yy-mm-dd",
                firstDay: 1,
                dayNamesMin: [ "Ni.", "Pn.", "Wt.", "Śr.", "Cz.", "Pt.", "So." ]
            });
        });

        $(function() {
            $( "#datepicker2" ).datepicker({
                dateFormat: "yy-mm-dd",
                firstDay: 1,
                dayNamesMin: [ "Ni.", "Pn.", "Wt.", "Śr.", "Cz.", "Pt.", "So." ]
            });
        });

        $(function() {
            $( "#datepicker3" ).datepicker({
                dateFormat: "yy-mm-dd",
                firstDay: 1,
                dayNamesMin: [ "Ni.", "Pn.", "Wt.", "Śr.", "Cz.", "Pt.", "So." ]
            });
        });
    </script>
    </body>
</html>

METsoft/offers/templates/offers/detail_confirm_delete.html
{% extends 'offers/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="text-center mt-5">
    <form method="POST">
        {% csrf_token %}
        <h2>Czy na pewno usunąć pozycję z oferty?</h2>
        <button class="btn btn-outline-danger">TAK</button>
        <a class="btn btn-outline-info" href="{% url 'offers' %}">Anuluj</a>
    </form>
</div>

{% endblock content %}

METsoft/offers/templates/offers/detail_form.html
{% extends 'offers/base.html' %}
{% block content %}
    <form class="fieldset" method="POST">
        {% csrf_token %}
        <br>
        <fieldset>
            {% if form.instance.pk  %}
                        <legend>EDYCJA</legend>
            {% else %}
                        <legend>DODAJ NOWY ODLEW</legend>
            {% endif %}
            <ul>
                {{ form.as_ul }}
                <input class="btn btn-outline-info" type="submit", name="save-detail" value="Zapisz">
                {% if form.instance.pk %}
                    <input class="btn btn-outline-info" type="submit" name="new-detail" value="Dodaj nowy detal">
                {% endif %}
            </ul>
        </fieldset>
    </form>
{% endblock content %}

METsoft/offers/templates/offers/detail_searching_form.html
{% extends 'offers/base.html' %}

{% block content %}
    <form method="POST" class="fieldset" >
        {% csrf_token %}
        <fieldset >
            <legend>Znajdź odlew</legend>
                <ul>
                    {{ form.as_ul}}
                    <button class="btn btn-outline-info">Wyszukaj</button>
                </ul>
        </fieldset>
    </form>
{% endblock content %}

METsoft/offers/templates/offers/detail_searching_results.html
{% extends 'offers/base.html' %}

{% block content %}
    <div class="text-center my-3">
        <h1>Znalezione odlewy</h1>
    </div>

    <table id="table" class="table table-bordered table-sm table-hover" style="width: 100%">
        <thead>
            <tr>
                <th>Lp</th>
                <th>Nr oferty</th>
                <th>Nazwa</th>
                <th>Nr rysunku</th>
                <th>Materiał</th>
                <th>Ciężar [kg]</th>
                <th>Il. szt.</th>
                <th>Uzysk[%]</th>
                <th>St. tr.</th>
                <th>Model</th>
                <th>Obr cieplna</th>
                <th>Obr. mech.</th>
                <th>Tolerancje</th>
                <th>Pochylenia</th>
                <th>Atest</th>
                <th>Odb. odlewu</th>
                <th>Klasa jakości</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th></th>
                <th>Nr oferty</th>
                <th>Nazwa</th>
                <th>Nr rysunku</th>
                <th>Materiał</th>
                <th>Ciężar [kg]</th>
                <th>Il. szt.</th>
                <th>Uzysk[%]</th>
                <th>St. tr.</th>
                <th>Model</th>
                <th>Obr cieplna</th>
                <th>Obr. mech.</th>
                <th>Tolerancje</th>
                <th>Pochylenia</th>
                <th>Atest</th>
                <th>Odb. odlewu</th>
                <th>Klasa jakości</th>
            </tr>
        </tfoot>
        <tbody>
            {% for obj in objects %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'offer-print' obj.offer.id %}">{{ obj.offer.offer_no }}</a></td>
                    <td>{{ obj.cast_name }}</td>
                    <td>{{ obj.drawing_no }}</td>
                    <td>{{ obj.mat.material }}</td>
                    <td>{{ obj.cast_weight|default_if_none:"" }}</td>
                    <td>{{ obj.pieces_amount }}</td>
                    <td>{{ obj.detail_yield|default_if_none:"" }}</td>
                    <td>{{ obj.difficulty }}</td>
                    <td>{{ obj.pattern }}</td>
                    <td>{{ obj.heat_treat }}</td>
                    <td>{{ obj.machining.machining }}</td>
                    <td>{{ obj.tolerances }}</td>
                    <td>{{ obj.tapers }}</td>
                    <td>{{ obj.atest }}</td>
                    <td>{{ obj.required }}</td>
                    <td>{{ obj.quality_class }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

{% block scripts %}
    <script defer>
        $(document).ready( function () {
            $('#table').DataTable({
                lengthMenu: [ [25, 50, 100, 200, 500], [25, 50, 100, 200, 500] ],
            });

            //Kod do wyszukiwania po kolumnach

            // Setup - add a text input to each footer cell
            $('#table tfoot th').each( function () {
                var title = $(this).text();
                $(this).html( '<input type="text" placeholder="Szukaj '+title+'" />' );
            } );

            // DataTable
            var table = $('#table').DataTable();

            // Apply the search
            table.columns().every( function () {
                var that = this;

                $( 'input', this.footer() ).on( 'keyup change', function () {
                    if ( that.search() !== this.value ) {
                        that
                            .search( this.value )
                            .draw();
                    }
                } );
            } );
        } );
    </script>
{% endblock scripts %}

METsoft/offers/templates/offers/material_form.html
{% extends 'offers/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form class="fieldset" method="POST">
        {% csrf_token %}
        <br>
        <fieldset>
            {% if form.instance.pk  %}
                        <legend>EDYTUJ MATERIAŁ</legend>
            {% else %}
                        <legend>DODAJ MATERIAŁ</legend>
            {% endif %}
            <ul>
                {{ form|crispy }}
                <button class="btn btn-outline-info">Zapisz</button>
            </ul>
        </fieldset>
    </form>
{% endblock content %}