METsoft/patterns/urls.py
from django.conf.urls import include
from django.urls import path, re_path
from django.views.generic import TemplateView
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r"patterns", views.PatternViewSet)

app_name = "patterns"
urlpatterns = [
    re_path("^api/", include(router.urls)),
    path(
        "",
        TemplateView.as_view(template_name="patterns/patterns_index.html"),
        name="patterns",
    ),
    path("<int:pk>/", views.PatternCardView.as_view(), name="pattern-card"),
    path("<int:pk>/edit", views.PatternUpdateView.as_view(), name="pattern-edit"),
    path("create/", views.PatternCreateView.as_view(), name="pattern-create"),
    path(
        "<int:pk>/status/",
        views.PatternStatusChangeView.as_view(),
        name="pattern-status-change",
    ),
    path("report/", views.PatternReportFormView.as_view(), name="pattern-report"),
]

METsoft/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, include
from django.views.generic import TemplateView
from rest_framework import routers

from . import views


router = routers.DefaultRouter()
router.register(r"logs", views.LogsViewSet, "logs")


urlpatterns = [
    path("", views.base),
    re_path("^api/", include(router.urls)),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="password-reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "redirect-after-login/", views.redirect_after_login, name="redirect-after-login"
    ),
    path(
        "logs/",
        TemplateView.as_view(template_name="users/logs_index.html"),
        name="logs",
    ),
]

METsoft/patterns/models.py
from datetime import date

from django.db import models
from django.urls import reverse


class PatternStatus(models.Model):
    status = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        db_table = "pattern_statuses"
        verbose_name_plural = "PatternStatuses"

    def __str__(self):
        return self.status


class Pattern(models.Model):
    customer = models.CharField("Nazwa firmy", max_length=100, blank=True, null=True)
    drawing_number = models.CharField(
        "Numer rysunku", max_length=100, blank=True, null=True
    )
    pattern_name = models.CharField(
        "Nazwa odlewu", max_length=100, blank=True, null=True
    )
    last_order = models.DateField(
        "Ostatnie zlecenie", blank=True, null=True, default=date.today
    )
    orders_amount = models.IntegerField(
        "Ilość zleceń", blank=True, null=True, default=1
    )
    area = models.FloatField("Powierzchnia", blank=True, null=True)
    layer_number = models.CharField(
        "Numer ułożenia", max_length=100, blank=True, null=True
    )
    layer_place = models.CharField(
        "Miejsce ułożenia", max_length=100, blank=True, null=True
    )
    material = models.CharField("Materiał", max_length=30, blank=True, null=True)
    cart_number = models.CharField(
        "Numer kartoteki", max_length=30, blank=True, null=True
    )
    pattern_index = models.CharField(
        "Numer indexu modelu", max_length=100, blank=True, null=True
    )
    verification = models.TextField("Weryfikacja", blank=True, null=True)
    remarks = models.TextField("Uwagi", blank=True, null=True)
    verification_date = models.CharField(
        "Data weryfikacji", max_length=30, blank=True, null=True, default=date.today
    )
    surname = models.CharField("Nazwisko", max_length=100, blank=True, null=True)
    status = models.ForeignKey(
        PatternStatus,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="status",
        default=1,
        limit_choices_to={"pk__lt": 8},
    )
    move_in = models.DateField(
        "Data zmiany statusu", blank=True, null=True, default=date.today
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "patterns"

    def __str__(self):
        return "{}".format(self.pattern_name)

    @staticmethod
    def get_absolute_url():
        return reverse("patterns:patterns")

    def get_not_using_time(self):
        if self.status.id in [4, 5, 6]:
            return None
        if self.last_order:
            diff = date.today() - self.last_order
            months = (diff.days // 365 * 12) + (diff.days % 365) / 30
            return int(months)
        return None

    def if_status_changed_update_history(self):
        previous_status = self.patternhistory_set.order_by("id").last()
        if previous_status.status != self.status:
            self.add_status_to_pattern_history()

    def add_status_to_pattern_history(self):
        PatternHistory.objects.create(
            pattern=self, status=self.status, date=self.move_in
        )


class PatternHistory(models.Model):
    pattern = models.ForeignKey(Pattern, on_delete=models.CASCADE, default=1)
    status = models.ForeignKey(PatternStatus, on_delete=models.DO_NOTHING, default=1)
    date = models.DateField()
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "pattern_history"
        verbose_name_plural = "PatternHistory"

METsoft/patterns/forms.py
from django import forms

from .models import Pattern


class PatternReportForm(forms.Form):

    customer1 = forms.CharField(
        max_length=50,
        required=True,
        label="Nazwa firmy nr 1",
        widget=forms.TextInput(attrs={"placeholder": "pole wymagane"}),
    )
    # customer2 = forms.CharField(max_length=50, required=False, label='Nazwa firmy nr 2')
    # customer3 = forms.CharField(max_length=50, required=False, label='Nazwa firmy nr 3')
    # not_using_time = forms.IntegerField(required=False,
    #                                     label='Czas nieużywania modelu',
    #                                     widget=forms.TextInput(attrs={'placeholder': 'ilość miesięcy'})
    #                                     )

    class Meta:
        # fields = ('customer1', 'customer2', 'customer3', 'not_using_time')
        fields = "customer1"


class PatternCreateForm(forms.ModelForm):

    material = forms.ChoiceField(
        choices=[
            ("", ""),
            ("staliwo", "staliwo"),
            ("żeliwo", "żeliwo"),
            ("kolorki", "kolorki"),
        ]
    )

    class Meta:
        model = Pattern
        fields = "__all__"
        widgets = {
            "verification": forms.Textarea(attrs={"rows": 1, "cols": 50}),
            "verification_date": forms.DateInput(
                attrs={"id": "datepicker2", "width": "230px"}, format="%Y-%m-%d"
            ),
            "remarks": forms.Textarea(attrs={"rows": 1, "cols": 50}),
            "move_in": forms.DateInput(
                attrs={"id": "datepicker1", "width": "230px"}, format="%Y-%m-%d"
            ),
            "last_order": forms.DateInput(
                attrs={"id": "datepicker3", "width": "230px"}, format="%Y-%m-%d"
            ),
        }


class PatternUpdateForm(forms.ModelForm):
    class Meta:
        model = Pattern
        fields = "__all__"
        widgets = {
            "verification": forms.Textarea(attrs={"rows": 1, "cols": 50}),
            "remarks": forms.Textarea(attrs={"rows": 1, "cols": 50}),
            "move_in": forms.DateInput(
                attrs={"id": "datepicker1", "width": "230px"}, format="%Y-%m-%d"
            ),
            "last_order": forms.DateInput(
                attrs={"id": "datepicker3", "width": "230px"}, format="%Y-%m-%d"
            ),
        }

METsoft/patterns/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Sum
from django.shortcuts import render
from django.views import generic
from rest_framework import viewsets

from .forms import PatternCreateForm, PatternReportForm, PatternUpdateForm
from .models import Pattern, PatternStatus
from .serializers import PatternSerializers


class PatternCardView(generic.DetailView):
    """ Showing history of status changes for the specific pattern"""

    model = Pattern
    template_name = "patterns/pattern_card.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["objects"] = self.object.patternhistory_set.all()
        return context


class PatternStatusChangeView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView
):
    """ Quick changing of the pattern status by clicking the appropriate button. """

    model = Pattern
    template_name = "patterns/pattern_status_change.html"
    permission_required = ["patterns.change_pattern"]
    fields = ["status"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Not possible to set status "Brak weryfikacji"
        context["statuses"] = PatternStatus.objects.all().exclude(pk=8)
        return context

    def get_success_url(self):
        """ If the pattern status is changed, add new status to the pattern history """
        Pattern.if_status_changed_update_history(self.object)
        return super().get_success_url()


class PatternReportFormView(generic.FormView):
    """ Generate a report included all patterns belonging to given customer """

    form_class = PatternReportForm
    template_name = "patterns/pattern_report_form.html"

    def post(self, request, *args, **kwargs):
        """ Preparing results from given data """
        patterns = Pattern.objects.filter(
            customer__icontains=request.POST.get("customer1")
        ).exclude(status__in=[4, 5, 6, 8])
        total_area = patterns.aggregate(total_area=Sum("area"))
        customers = patterns.values("customer").distinct()

        context = {
            "objects": patterns,
            "total_area": total_area,
            "customers": customers,
        }
        return render(request, "patterns/pattern_report_results.html", context)


class PatternViewSet(viewsets.ReadOnlyModelViewSet):
    """ Show all patterns in database"""

    queryset = Pattern.objects.all().order_by("-id")
    serializer_class = PatternSerializers


class PatternCreateView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView
):
    """ Adding new pattern to database """

    model = Pattern
    form_class = PatternCreateForm
    permission_required = ["patterns.add_pattern"]

    def get_success_url(self):
        """ Add record with initial status to the pattern history"""
        Pattern.add_status_to_pattern_history(self.object)
        return super().get_success_url()


class PatternUpdateView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView
):
    """ Changing the pattern data"""

    model = Pattern
    form_class = PatternUpdateForm
    permission_required = ["patterns.change_pattern"]

    def get_success_url(self):
        """ If the pattern status is changed, add new status to the pattern history """
        Pattern.if_status_changed_update_history(self.object)
        return super().get_success_url()

METsoft/patterns/templates/patterns/pattern_card.html
{% extends 'offers/base.html' %}

{% block content %}
    <div class="text-center my-3">
        <h2>Karta modelu</h2>
    </div>

    <div style="font-size: 22px; text-align:center;padding:20px">
        <label style="padding:20px">Nazwa firmy:<b>{{ pattern.customer }}</b></label>
        <label style="padding:20px">Nazwa odlewu:<b>{{ pattern.pattern_name }}</b></label>
        <label style="padding:20px">Numer rysunku:<b>{{ pattern.drawing_number }}</b></label>
    </div>

    <table class="table table-bordered table-striped table-sm table-hover" style="width:60%; margin:auto">
        <thead>
            <tr>
                <th>Lp</th>
                <th>Operacja</th>
                <th>Data</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in objects %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ obj.status.status }}</td>
                    <td>{{ obj.date|date:"Y-m-d" }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock content %}

METsoft/patterns/templates/patterns/pattern_form.html
{% extends 'offers/base.html' %}

{% block content %}
    <form class="fieldset" method="POST">
        {% csrf_token %}
        <br>
        <fieldset>
            {% if form.instance.pk  %}
                <legend>EDYTUJ MODEL</legend>
            {% else %}
                <legend>DODAJ MODEL</legend>
            {% endif %}
            <ul>
                {{ form.as_ul }}
                <button class="btn btn-outline-info">Zapisz</button>
            </ul>
        </fieldset>
    </form>
{% endblock content %}

METsoft/patterns/templates/patterns/pattern_report_form.html
{% extends 'offers/base.html' %}

{% block content %}
    <form method="POST" class="fieldset" target="_blank">
        {% csrf_token %}
        <fieldset>
            <legend>Dane do raportu</legend>
            <ul>
                {{ form.as_ul }}
                <button class="btn btn-outline-info">Generuj</button>
            </ul>
        </fieldset>
    </form>
{% endblock content %}

METsoft/patterns/templates/patterns/pattern_report_results.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>METsoft - Raport</title>
    <style>
        table {
            border-collapse: collapse;
            border-spacing: 0;
            /*width: 50%; */
            border: 1px solid #0c0c0c;
            table-layout: auto;
            margin: 0 auto;
            font-size: 12px;
        }

        th, td {
            text-align: left;
            padding: 2px;
            border: 1px solid #23527c ;
        }

        .text-right {
            text-align: right;
        }

        h2 {
            text-align: center;
            margin: 0;
            font-size: 20px;
        }
    </style>

</head>
<body>
    <h2>Modele firm:
        {% for item in customers %}
            {{ item.customer }};
        {% endfor %}
    </h2>
    <table width=640px>
        <tr>
            <th>Lp</th>
            <th>Klient</th>
            <th>Nazwa rysunku</th>
            <th>Nazwa modelu</th>
            <th>Ilość m2</th>
            <th>Ostatnie zlecenie (rok)</th>
            <th>Okres nieużywania modelu (m-ce)</th>
        </tr>

        {% for obj in objects %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ obj.customer }}</td>
                <td>{{ obj.drawing_number }}</td>
                <td>{{ obj.pattern_name }}</td>
                <td class="text-right">{{ obj.area|floatformat:"2" }}</td>
                <td class="text-right">{{ obj.last_order|date:"Y-m-d" }}</td>
                <td class="text-right">{{ obj.get_not_using_time|default_if_none:"" }}</td>
            </tr>
        {% endfor %}

        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>Razem</td>
            <td class="text-right">{{ total_area.total_area|floatformat:"2" }}</td>
            <td></td>
            <td></td>
        </tr>
    </table>
</body>
</html>

METsoft/patterns/templates/patterns/pattern_status_change.html
{% extends 'offers/base.html' %}

{% block content %}

    <div class="text-center my-3">
        <h2>Szybka zmiana statusu</h2>
    </div>

    <div style="font-size: 22px; text-align:center;padding:20px">
        <label style="padding:20px">Nazwa firmy: <b>{{ pattern.customer }}</b></label>
        <label style="padding:20px">Nazwa odlewu: <b>{{ pattern.pattern_name }}</b></label>
        <label style="padding:20px">Numer rysunku: <b>{{ pattern.drawing_number }}</b></label>
    </div>

    <div style="text-align:center">
        {% for status in statuses %}
            <div style="display:inline-block; padding:30px 30px">
                <form method="POST" action="{% url 'patterns:pattern-status-change' pattern.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="status" value="{{ status.id }}">
                    <button style="font-size:40px">{{ status.status }}</button>
                </form>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

METsoft/patterns/templates/patterns/patterns_index.html
{% extends 'offers/base.html' %}

{% block content %}
<div class="text-center my-3">
        <h1>Rejestr modeli</h1>
</div>

        <table id="patterns" class="table table-bordered table-sm table-hover" style="width: 100%">
            <thead>
                <tr>
                    <th>Nazwa firmy</th>
                    <th>Numer rysunku</th>
                    <th>Nazwa odlewu</th>
                    <th>Ostatnie zlecenie</th>
                    <th>Il. zleceń</th>
                    <th>Powierz- chnia</th>
                    <th>Numer ułożenia</th>
                    <th>Miejsce ułożenia</th>
                    <th>Materiał</th>
                    <th>Numer kartoteki</th>
                    <th>Numer indeksu modelu</th>
                    <th>Weryfikacja</th>
                    <th>Uwagi</th>
                    <th>Data weryfikacji</th>
                    <th>Nazwisko</th>
                    <th>Status</th>
                    <th>Data zmiany statusu</th>
                    <th>Czas nieużywania modelu</th>
                    <th>Operacje</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Nazwa firmy</th>
                    <th>Numer rysunku</th>
                    <th>Nazwa odlewu</th>
                    <th>Ostatnie zlecenie</th>
                    <th>Il. zleceń</th>
                    <th>Powierz- chnia</th>
                    <th>Numer ułożenia</th>
                    <th>Miejsce ułożenia</th>
                    <th>Materiał</th>
                    <th>Numer kartoteki</th>
                    <th>Numer indeksu modelu</th>
                    <th>Weryfikacja</th>
                    <th>Uwagi</th>
                    <th>Data weryfikacji</th>
                    <th>Nazwisko</th>
                    <th>Status</th>
                    <th>Data zmiany statusu</th>
                    <th>Czas nieużywania modelu</th>
                    <th>Operacje</th>
                </tr>
            </tfoot>
        </table>
{% endblock content %}

{% block scripts %}
     <script defer>
            $(document).ready( function () {
                $('#patterns').DataTable({
                    lengthMenu: [ [25, 50, 100, 200, 500], [25, 50, 100, 200, 500] ],
                    order: [[18, 'desc']],
                    serverSide: true,
                    processing: true,
                    language: { "processing": "Ładowanie strony" },
                    ajax: '/patterns/api/patterns/?format=datatables',
                    columns: [
                        { data: 'customer', name: 'customer' },
                        { data: 'drawing_number', name: 'drawing_number' },
                        { data: 'pattern_name', name: 'pattern_name' },
                        { data: 'last_order', name: 'last_order' },
                        { data: 'orders_amount', name: 'orders_amount' },
                        { data: 'area', name: 'area',
                            render: $.fn.dataTable.render.number( ' ', ',', 2)
                        },
                        { data: 'layer_number', name: 'layer_number' },
                        { data: 'layer_place', name: 'layer_place' },
                        { data: 'material', name: 'material' },
                        { data: 'cart_number', name: 'cart_number' },
                        { data: 'pattern_index', name: 'pattern_index' },
                        { data: 'verification', name: 'verification' },
                        { data: 'remarks', name: 'remarks' },
                        { data: 'verification_date', name: 'verification_date' },
                        { data: 'surname', name:'surname'},
                        { data: 'status.status'},
                        { data: 'move_in', name:'move_in' },
                        { data: 'get_not_using_time', searchable: false },
                        { data: 'id',
                            "fnCreatedCell":function(nTd, sData, oData, iRow, iCol){
                                $(nTd).html('{% if perms.patterns %}<a class="iframe" href="/patterns/' + sData + '/edit">Edytuj</a><br> ' +
                                            '<a class="iframe" href="/patterns/' + sData + '/status">Status</a><br>{% endif %}' +
                                            '<a class="iframe" href="/patterns/' + sData + '">Karta</a>');
                            }
                        }
                    ],
                });

                 //Kod do wyszukiwania po kolumnach

                // Setup - add a text input to each footer cell
                $('#patterns tfoot th').each( function () {
                    var title = $(this).text();
                    $(this).html( '<input type="text" placeholder="Szukaj '+title+'" />' );
                } );

                // DataTable
                var table = $('#patterns').DataTable();

                // Apply the search
                table.columns().every( function () {
                    var that = this;

                    $( 'input', this.footer() ).on( 'keyup change', function () {
                        if ( that.search() !== this.value ) {
                            that
                                .search( this.value )
                                .draw();
                        }
                    } );
                } );
            });
    </script>
{% endblock scripts %}


<!--                            $(nTd).html(<a class="iframe" href="/patterns/' + sData + '/edit">Edytuj</a><br>' +-->
<!--                                '<a class="iframe" href="/patterns_status/' + sData + '">Status</a><br>' +-->
<!--                                '<a class="iframe" href="/patterns/' + sData + '">Karta</a>)-->